### ISSUE TITLE
Build with ESM

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/whook#102]
Node14 now supports ESM, when AWSLambda and GCP will upgrade to it, we will be able to build ESM modules. Here is a to do list to achieve this:
- [x] ensure dependencies are doing ESM well (`type: 'module'` in `package.json` https://nodejs.org/api/packages.html#packages_type and .js files are ESM , ensure imports have file extension https://github.com/JedWatson/react-select/issues/4253 )
- [x] tweak the compiler configuration: https://github.com/nfroidure/whook/blob/master/packages/whook-aws-lambda/src/services/compiler.ts#L141-L145
- [x] consider to use TypeScript transpiler only since babel were used for supporting modules only ( TS4.7 seems to be on its way to full ESM support https://devblogs.microsoft.com/typescript/announcing-typescript-4-7-beta/ )
- [x] consider AWS Lambda (https://aws.amazon.com/fr/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/) 
- consider GCP integrations https://cloud.google.com/functions/docs/concepts/nodejs-runtime#using_es_modules : reported to https://github.com/nfroidure/whook/issues/178
- [x] fix `common-services` to resolve modules with `import.meta` https://github.com/nfroidure/common-services/issues/20
- [x] fix the [problem with `ts-node`](https://github.com/TypeStrong/ts-node/issues/1997):  (maybe use [tsx](https://github.com/nfroidure/whook/issues/155)

**Comment by nfroidure** [comment]
Use esbuild instead since it supports ts natively and is made for bundling : https://github.com/nfroidure/whook/pull/105

**Comment by nfroidure** [comment]
Sadly AWS lambda support is fake since the layers doesn't support ESM... see https://github.com/vibe/aws-esm-modules-layer-support

**Comment by nfroidure** [comment]
Jest is not supporting ESM fully, will lurk its progress: https://github.com/jestjs/jest/issues/14923
